services:
  nats:
    container_name: nats
    image: nats:2.11.6-alpine
    command:
      - '--jetstream'
      - '--store_dir=/var/lib/nats/data'
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - nats-data:/var/lib/nats/data # TODO: ^6 dry
    restart: on-failure
    # TODO: add healthcheck
  etcd:
    container_name: etcd
    image: quay.io/coreos/etcd:v3.5.21
    ports:
      - 2379:2379
      - 2380:2380
    command:
      - 'etcd'
      - '--name=etcd-1'
      - '--initial-advertise-peer-urls=http://etcd-1:2380'
      - '--listen-peer-urls=http://0.0.0.0:2380'
      - '--listen-client-urls=http://0.0.0.0:2379'
      - '--advertise-client-urls=http://etcd-1:2379'
      - '--heartbeat-interval=250'
      - '--election-timeout=1250'
    volumes:
      - etcd-data:/var/lib/etcd/data
    restart: on-failure
    # TODO: https://github.com/guessi/docker-compose-etcd/blob/master/docker-compose.yml

volumes:
  nats-data:
  etcd-data:

