services:
  nats:
    container_name: nats
    image: nats:2.11.6-alpine
    command:
      - '--jetstream'
      - '--store_dir=/var/lib/nats/data'
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    volumes:
      - nats-data:/var/lib/nats/data # TODO: ^6 dry
    restart: on-failure
    # TODO: add healthcheck

volumes:
  nats-data:


